#!/usr/bin/env bash

set -e -o pipefail

# From https://stackoverflow.com/a/4774063
REPO_DIR="$( cd -- "$(dirname "$0")/.." >/dev/null 2>&1 ; pwd -P )"

PACKAGES_DIR="$REPO_DIR/packages"
PACKAGE_PATHS="$(find "$PACKAGES_DIR" -name '*-action' -type d -not -wholename '*/node_modules/*')"
for PACKAGE_PATH in $PACKAGE_PATHS; do
  RELATIVE_PATH="${PACKAGE_PATH#"$PACKAGES_DIR/"}"
  ACTION_DIR="$REPO_DIR/actions/$RELATIVE_PATH"
  RELATIVE_SOURCE="packages/$RELATIVE_PATH/action.yaml"
  echo "Building package ${RELATIVE_PATH}..."
  mkdir -p "$ACTION_DIR"
  {
    echo "# This file is a copy of $RELATIVE_SOURCE."
    echo "# Changes should be made to $RELATIVE_SOURCE, not this file."
    echo ""
    cat "$PACKAGE_PATH/action.yaml"
  } > "$ACTION_DIR/action.yaml"
  ACTION_PATHS="$(find "$PACKAGE_PATH" -type f -name 'action.ts' -not -wholename '*/node_modules/*')"
  for ACTION_PATH in $ACTION_PATHS; do
    echo "Building action ${ACTION_PATH}..."
    pnpm exec esbuild "$ACTION_PATH" --bundle --platform=node --target=node20 --outfile="$ACTION_DIR/index.js" --minify
  done
done
